version: "3"

services:
  api:
    container_name: vepa
    build: ./
    restart: unless-stopped
    volumes:
      - ./logs:/var/www/vepa/logs
    env_file:
      - ./docker.env
    ports:
      - "4000:4000"

